modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="safidian" #mandatory

version="1.15.2-1.2.0" #mandatory

displayName="Safidian Mod V1.2" #mandatory

logoFile="examplemod.png" #optional

credits="Thanks for Endeermon" #optional

authors="Ziguirr" #optional

description='''Safidian Mod: Que tal um desafio além do diamante?
Itens de Safidian são muito mais poderosos!

==================================================================

-> Novo Bloco, Ferramentas e Minério!'''

[[dependencies.examplemod]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[31,)" #mandatory

    ordering="NONE"

    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
